package vista;

import java.awt.Dimension;
import javax.swing.JDesktopPane;

public class Menu extends javax.swing.JFrame {
    
    public static JDesktopPane jDesktopPane_menu;

    public Menu() {
        initComponents();
        this.setSize(new Dimension(1280, 832));
        // Maximiza la ventana en toda la pantalla
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.setTitle("Sistema de Ventas");
        
        this.setLayout(null);
        jDesktopPane_menu = new JDesktopPane();
        
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        this.jDesktopPane_menu.setBounds(0, 0, ancho, (alto - 110));
        this.add(jDesktopPane_menu);
        
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuItem_NuevoUsuario = new javax.swing.JMenuItem();
        MenuItem_GestionarUsuario = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuItem_NuevoCliente = new javax.swing.JMenuItem();
        MenuItem_GestionarCliente = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        MenuItem_NuevoProducto = new javax.swing.JMenuItem();
        MenuItem_GestionarProductos = new javax.swing.JMenuItem();
        MenuItem_ActualizarStock = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        MenuItem_NuevaCategoria = new javax.swing.JMenuItem();
        MenuItem_GestionarCategorias = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        MenuItem_NuevaVenta = new javax.swing.JMenuItem();
        MenuItem_GestionarVentas = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        MenuItem_ReporteClientes = new javax.swing.JMenuItem();
        MenuItem_ReporteProductos = new javax.swing.JMenuItem();
        MenuItem_ReporteCategorias = new javax.swing.JMenuItem();
        MenuItem_ReporteVentas = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        MenuItem_VerHistorial = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        MenuItem_CerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jMenuBar1.setPreferredSize(new java.awt.Dimension(1280, 60));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Menu_Usuarios.png"))); // NOI18N
        jMenu1.setText("Usuario");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jMenu1.setPreferredSize(new java.awt.Dimension(160, 50));

        MenuItem_NuevoUsuario.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        MenuItem_NuevoUsuario.setText("Nuevo Usuario");
        MenuItem_NuevoUsuario.setPreferredSize(new java.awt.Dimension(160, 30));
        MenuItem_NuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_NuevoUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItem_NuevoUsuario);

        MenuItem_GestionarUsuario.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        MenuItem_GestionarUsuario.setText("Gestionar Usuarios");
        MenuItem_GestionarUsuario.setPreferredSize(new java.awt.Dimension(160, 30));
        jMenu1.add(MenuItem_GestionarUsuario);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Menu_Clientes.png"))); // NOI18N
        jMenu2.setText("Cliente");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jMenu2.setPreferredSize(new java.awt.Dimension(160, 50));

        MenuItem_NuevoCliente.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        MenuItem_NuevoCliente.setText("Nuevo Cliente");
        MenuItem_NuevoCliente.setPreferredSize(new java.awt.Dimension(160, 30));
        jMenu2.add(MenuItem_NuevoCliente);

        MenuItem_GestionarCliente.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        MenuItem_GestionarCliente.setText("Gestionar Clientes");
        MenuItem_GestionarCliente.setPreferredSize(new java.awt.Dimension(160, 30));
        MenuItem_GestionarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_GestionarClienteActionPerformed(evt);
            }
        });
        jMenu2.add(MenuItem_GestionarCliente);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu_productos.png"))); // NOI18N
        jMenu3.setText("Producto");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jMenu3.setPreferredSize(new java.awt.Dimension(160, 50));

        MenuItem_NuevoProducto.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        MenuItem_NuevoProducto.setText("Nuevo Producto");
        MenuItem_NuevoProducto.setPreferredSize(new java.awt.Dimension(160, 30));
        jMenu3.add(MenuItem_NuevoProducto);

        MenuItem_GestionarProductos.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        MenuItem_GestionarProductos.setText("Gestionar Productos");
        MenuItem_GestionarProductos.setPreferredSize(new java.awt.Dimension(160, 30));
        jMenu3.add(MenuItem_GestionarProductos);

        MenuItem_ActualizarStock.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        MenuItem_ActualizarStock.setText("Actualizar Stock");
        MenuItem_ActualizarStock.setPreferredSize(new java.awt.Dimension(160, 30));
        jMenu3.add(MenuItem_ActualizarStock);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu_categorias.png"))); // NOI18N
        jMenu4.setText("Categoria");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jMenu4.setPreferredSize(new java.awt.Dimension(160, 50));

        MenuItem_NuevaCategoria.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        MenuItem_NuevaCategoria.setText("Nueva Categoria");
        MenuItem_NuevaCategoria.setPreferredSize(new java.awt.Dimension(160, 30));
        MenuItem_NuevaCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_NuevaCategoriaActionPerformed(evt);
            }
        });
        jMenu4.add(MenuItem_NuevaCategoria);

        MenuItem_GestionarCategorias.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        MenuItem_GestionarCategorias.setText("Gestionar Categorias");
        MenuItem_GestionarCategorias.setPreferredSize(new java.awt.Dimension(160, 30));
        MenuItem_GestionarCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_GestionarCategoriasActionPerformed(evt);
            }
        });
        jMenu4.add(MenuItem_GestionarCategorias);

        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu_facturacion.png"))); // NOI18N
        jMenu5.setText("Facturacion");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jMenu5.setPreferredSize(new java.awt.Dimension(160, 50));

        MenuItem_NuevaVenta.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        MenuItem_NuevaVenta.setText("Nueva Venta");
        MenuItem_NuevaVenta.setPreferredSize(new java.awt.Dimension(160, 30));
        jMenu5.add(MenuItem_NuevaVenta);

        MenuItem_GestionarVentas.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        MenuItem_GestionarVentas.setText("Gestionar Ventas");
        MenuItem_GestionarVentas.setPreferredSize(new java.awt.Dimension(160, 30));
        jMenu5.add(MenuItem_GestionarVentas);

        jMenuBar1.add(jMenu5);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Menu_Reporte.png"))); // NOI18N
        jMenu6.setText("Reporte");
        jMenu6.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jMenu6.setPreferredSize(new java.awt.Dimension(160, 50));

        MenuItem_ReporteClientes.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        MenuItem_ReporteClientes.setText("Reportes Clientes");
        MenuItem_ReporteClientes.setPreferredSize(new java.awt.Dimension(160, 30));
        jMenu6.add(MenuItem_ReporteClientes);

        MenuItem_ReporteProductos.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        MenuItem_ReporteProductos.setText("Reportes Productos");
        MenuItem_ReporteProductos.setPreferredSize(new java.awt.Dimension(160, 30));
        jMenu6.add(MenuItem_ReporteProductos);

        MenuItem_ReporteCategorias.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        MenuItem_ReporteCategorias.setText("Reportes Categorias");
        MenuItem_ReporteCategorias.setPreferredSize(new java.awt.Dimension(160, 30));
        MenuItem_ReporteCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_ReporteCategoriasActionPerformed(evt);
            }
        });
        jMenu6.add(MenuItem_ReporteCategorias);

        MenuItem_ReporteVentas.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        MenuItem_ReporteVentas.setText("Reportes Ventas");
        MenuItem_ReporteVentas.setPreferredSize(new java.awt.Dimension(160, 30));
        jMenu6.add(MenuItem_ReporteVentas);

        jMenuBar1.add(jMenu6);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Menu_Historial.png"))); // NOI18N
        jMenu7.setText("Historial");
        jMenu7.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jMenu7.setPreferredSize(new java.awt.Dimension(160, 50));

        MenuItem_VerHistorial.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        MenuItem_VerHistorial.setText("Ver Historial");
        MenuItem_VerHistorial.setPreferredSize(new java.awt.Dimension(160, 30));
        jMenu7.add(MenuItem_VerHistorial);

        jMenuBar1.add(jMenu7);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu_cerrarSesion.png"))); // NOI18N
        jMenu8.setText("Salir");
        jMenu8.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jMenu8.setPreferredSize(new java.awt.Dimension(160, 50));

        MenuItem_CerrarSesion.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        MenuItem_CerrarSesion.setText("Cerrar Sesion");
        MenuItem_CerrarSesion.setPreferredSize(new java.awt.Dimension(160, 30));
        MenuItem_CerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_CerrarSesionActionPerformed(evt);
            }
        });
        jMenu8.add(MenuItem_CerrarSesion);

        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItem_NuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_NuevoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuItem_NuevoUsuarioActionPerformed

    private void MenuItem_GestionarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_GestionarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuItem_GestionarClienteActionPerformed

    private void MenuItem_ReporteCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_ReporteCategoriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuItem_ReporteCategoriasActionPerformed

    private void MenuItem_NuevaCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_NuevaCategoriaActionPerformed
        InterCategoria interCategoria = new InterCategoria();
        jDesktopPane_menu.add(interCategoria);
        interCategoria.setVisible(true);
    }//GEN-LAST:event_MenuItem_NuevaCategoriaActionPerformed

    private void MenuItem_GestionarCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_GestionarCategoriasActionPerformed
        
    }//GEN-LAST:event_MenuItem_GestionarCategoriasActionPerformed

    private void MenuItem_CerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_CerrarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuItem_CerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuItem_ActualizarStock;
    private javax.swing.JMenuItem MenuItem_CerrarSesion;
    private javax.swing.JMenuItem MenuItem_GestionarCategorias;
    private javax.swing.JMenuItem MenuItem_GestionarCliente;
    private javax.swing.JMenuItem MenuItem_GestionarProductos;
    private javax.swing.JMenuItem MenuItem_GestionarUsuario;
    private javax.swing.JMenuItem MenuItem_GestionarVentas;
    private javax.swing.JMenuItem MenuItem_NuevaCategoria;
    private javax.swing.JMenuItem MenuItem_NuevaVenta;
    private javax.swing.JMenuItem MenuItem_NuevoCliente;
    private javax.swing.JMenuItem MenuItem_NuevoProducto;
    private javax.swing.JMenuItem MenuItem_NuevoUsuario;
    private javax.swing.JMenuItem MenuItem_ReporteCategorias;
    private javax.swing.JMenuItem MenuItem_ReporteClientes;
    private javax.swing.JMenuItem MenuItem_ReporteProductos;
    private javax.swing.JMenuItem MenuItem_ReporteVentas;
    private javax.swing.JMenuItem MenuItem_VerHistorial;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
